### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by anton-khodak** [common-workflow-language/gxargparse#1]
As @mr-c mentioned in a private conversation, Galaxy will be gaining CWL support, and the development of the original gxargparse basically stopped, so Galaxy specific parts can be ripped off. I need them now as a sample, but as soon as CWL tool wrapper will be finished, I'll remove them as much as the docs. Should the repository bear the old name along with that?

/cc @brainstorm

**Comment by brainstorm** [comment]
Good points. I understand you would like to cleanup and focus on, for instance, argparse support for now. I guess that a separate repository with a more generic name such as `argparse2cwl` would make more sense?

What's your take on this @mr-c?

**Comment by mr-c** [comment]
The new name is fine, but no need to create a new repo: we can have this
one renamed.

On Mon, Apr 25, 2016 at 4:12 PM, Roman Valls Guimerà <
notifications@github.com> wrote:

> Good points. I understand you would like to cleanup and focus on, for
> instance, argparse support for now. I guess that a separate repository with
> a more generic name such as argparse2cwl would make more sense?
> 
> What's your take on this @mr-c https://github.com/mr-c?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/common-workflow-language/gxargparse/issues/1#issuecomment-214351118

## 

Michael R. Crusoe                          michael.crusoe@gmail.com
Community Engineer                 Common Workflow Language project
_https://impactstory.org/u/0000-0002-2961-9670
https://impactstory.org/u/0000-0002-2961-9670_   +32 (0) 2 808 25 52
                                                    +1 480 627 9108

**Comment by jmchilton** [comment]
It would seem we should work on a unified code base - I'd strongly urge you not to rip the Galaxy parts out - this seems actively hostile to a large and active community of developers that you should want to embrace the CWL.

**Comment by mr-c** [comment]
Hey @jmchilton 

No intent to be hostile to Galaxy here. Since it is likely that Galaxy will support CWL tool definitions by the time this is done we thought it might be simpler to remove the Galaxy XML code paths to simplify the code base.

**Comment by jmchilton** [comment]
- gxparse development has stalled but I don't think anyone considers it a dead project - I want it to be awesome for Galaxy tools and I want to add it to planemo.
- Just because CWL tools might be available in Galaxy doesn't mean Galaxy tool XML files are going away and they will likely provide a superior Galaxy experience for some time.
- Keeping two implementations in the code will ensure abstractions exist to keep the code general enough to allow additional tooling formats - it doesn't advance a CWL agenda but it is probably good for this codebase. It has already proven interesting enough to attract another tool format.

If you rip the Galaxy stuff out this is a full fork of the project - you can do a full fork - the license absolutely allows it. But doing a full fork of a project where the original shareholders are interested in maintaining it isn't a good way to do open source in my experience and I would hope for better from the CWL community.

**Comment by mr-c** [comment]
Sounds like we should keep the codebase whole; thank you @jmchilton for helping us understand that.

@anton-khodak I suggest keeping the name for now. We can reconsider the name at the end of the summer.

**Comment by jmchilton** [comment]
I would wholly endorse a more general name - `argparse2tool` or something. I don't see a need to maintain Galaxy branding on this - I just want us all to work together.

**Comment by hexylena** [comment]
Echoing @jmchilton, would be quite happy to see updates upstreamed, CWL folks. 

It's true, I've been busy with teaching and haven't been able to make any of the planned improvements to gxargparse, but I'd be open to whatever changes are required for y'all.

**Comment by mr-c** [comment]
Thank you @erasche, we will ensure that the result is still usable and upstreamable. I'm going to close this issue for now.

**Comment by brainstorm** [comment]
@erasche If you don't mind, could you add @mr-c, @anton-khodak and myself as contributors to this repo? I'm thinking on enabling future Github integrations with i.e TravisCI for testing and automation, so asking for permissions/accesss in advance (we're not there yet ;)).

Thanks!

**Comment by hexylena** [comment]
Sure thing.
