### ISSUE TITLE
optional CWL tool output definitions in external file

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/gxargparse#6]
Hey @anton-khodak, this is looking great!

In the resulting CWL tool definition I see that the output sections are all blank.

One way to fix that is to accept a file with the definitions written by hand.

**Comment by anton-khodak** [comment]
They are blank because now output section is filled only when an argument is an instance of `FileType` with write mode, and most output arguments are not specified that complicated way. I can put all arguments that contain 'output' keyword in their name into output section, however, it is often not what that argument is designed for (i.e. argument '--output-dir', and we assign it `type: File`) and such wrapper must be corrected by hand. 

Please, clarify, what do you mean by accepting a file with the definitions written by hand.

**Comment by brainstorm** [comment]
Ouch, sorry guys, just saw this issue **after** merging the PR :/ I guess one more reason to have those tests (and CI) in place as soon as possible...

**Comment by mr-c** [comment]
Hey Anton,

This issue isn't a criticism, it is just intended to point out the next steps.

Smart thinking about looking for `FileType` with write mode.

The idea is that the user provides the CWL tool definition `outputs` section in a file:

```
outputs:
  - id: '#output1'
    type: File
    outputBinding:
      glob: output1

  - id: "#output_log"
    type: File
    outputBinding:
      glob: 'output1.log’
```

Then the path to that file could be passed as the value of an optional parameter:

```
python-script.py --generate_cwl_tool --generate_cwl_tool_output_template outputs.cwl
```

And the user-provided `outputs` would be used in the generated CWL definition.

**Comment by anton-khodak** [comment]
No problem, I just didn't quite catch your point) I see now what you meant, I will add that option.

**Comment by anton-khodak** [comment]
I made this option available only for one file now. Otherwise, a user has to pass multiple files or a directory name with output files, each of the files must match the name of the corresponding tool, it is rather sophisticated. What is your opinion, will it be a widespread feature? Users can append output sections straight into the formed tools.

**Comment by mr-c** [comment]
I think you're saying that this works for programs that don't use subcommands? That's great!

We can re-evaluate the need to add this for programs with subcommands later. Please document the (strategic) limitation and close this issue for now.

Thanks!

**Comment by anton-khodak** [comment]
Exactly, it works fine for programs without subcommands. It is not hard to implement this option for programs with subcommands, it is just a question of how usable it will be.
